all: plot_equal_order_0

plot_equal_order_0:
	python3 view_equal_order.py 0 -category all
	python3 view_equal_order.py 0 -category gps
	python3 view_equal_order.py 0 -category far
	python3 view_equal_order.py 0 -category south
