all: compilers petsc firedrake

compilers:
	source install_compilers.sh

python3:
	source install_python3.sh

petsc:
	source install_petsc.sh

firedrake:
	source install_firedrake.sh

basic:
	source install_firedrake_no_adapt.sh
