all: fixed_mesh

fixed_mesh:
	@echo "Solving inundated beach problem on a fixed mesh..."
	@python3 run_fixed_mesh.py

moving_mesh:
	@echo "Solving inundated beach problem on a moving mesh..."
	@python3 run_moving_mesh.py
